terascope/kafka-assets

asset/asset.json, asset/teraslice_kafka_reader/index.js, asset/teraslice_kafka_sender/index.js
This is a standing pr to update error handling and implement a better guard on commit sync.
This was tested on a single computer with three brokers. I will stop all three brokers half way through the job, let the workers hang for 3-5 minutes and then restart the brokers. I would then see a rebalance call and then the workers continue. The end amount would be more than the expected (expected 1,000,000 got 1,120,000). It seems the commit did not go through before the rebalance happened and that it reprocessed the slice and a bit more. There are no signs that partial slice completion of 10k docs occurred. This need more live tests
=> updated code for better error handling

asset/asset.json, asset/package.json, asset/teraslice_kafka_reader/index.js, asset/yarn.lock, package.json, yarn.lock
- better error handling when creating DataEntities
- store more metadata in the `DataEntity`
- update `job-components`
- add option `bad_record_action` to reader. This can set to one of the following:
- `none` - (default) do nothing with the record
- `log` - log the record and error
- `throw` - throw the original error and fail the slice
=> v1.2.1 better error handling and metadata for DataEntities

README.md, asset/asset.json, asset/package.json, asset/src/_kafka_helpers/index.ts, asset/src/kafka_reader/fetcher.ts, docs/kafka_dead_letter/USAGE.md, docs/kafka_reader/USAGE.md, docs/kafka_sender/USAGE.md, package.json
There was a regression in 2.1.2 where there is no key and the fetcher would default it to an empty string when it should be set to null.
=> v2.1.3 Fix case when using no key and elasticsearch bulk

asset/asset.json, asset/package.json, asset/src/_kafka_clients/base-client.ts, asset/src/_kafka_clients/consumer-client.ts, package.json, test/base-client-spec.ts
`node-rdkafka` introduced a [breaking change](https://github.com/Blizzard/node-rdkafka/commit/575c791738aaf1e5053fb86bb6731a0883edd949#diff-00945053400287f301a6b6a43c5f69ad) to the offset.commit callback. I fixed it so its backwards and forwards compatible.
@erik-stephens this should fix some of the partition behind log messages we've seeing.
=> v2.1.7 fix commit.offset handler

asset/yarn.lock, packages/terafoundation_kafka_connector/package.json, yarn.lock
Teraslice got auto-upgraded to node-rdkafka 2.7.1 which doesn't work right. This PR locks it down to 2.7.0.
=> Lock down node-rdkafka version to exactly 2.7.0

README.md, asset/asset.json, asset/package.json, asset/src/_kafka_clients/base-client.ts, asset/src/_kafka_clients/consumer-client.ts, asset/src/kafka_reader/fetcher.ts, asset/src/kafka_reader/interfaces.ts, asset/src/kafka_reader/schema.ts, asset/yarn.lock, package.json, packages/terafoundation_kafka_connector/package.json, packages/terafoundation_kafka_connector/src/index.ts, yarn.lock
- Update `node-rdkafka` and bump connector `v0.5.0`
- Add `use_commit_sync` option to `kafka_reader` to test using commit async vs sync
=> v2.2.0 - Update node-rdkafka and add use_commit_async option

.travis.yml, asset/asset.json, asset/package.json, asset/src/_kafka_clients/base-client.ts, asset/src/_kafka_clients/consumer-client.ts, asset/src/_kafka_clients/producer-client.ts, asset/src/kafka_dead_letter/api.ts, asset/src/kafka_reader/fetcher.ts, asset/src/kafka_sender/processor.ts, package.json, packages/terafoundation_kafka_connector/package.json, packages/terafoundation_kafka_connector/src/index.ts, packages/terafoundation_kafka_connector/src/interfaces.ts, test/helpers/kafka-admin.ts, test/helpers/kafka-data.ts, yarn.lock
Adds support for node 12 by using [`@terascope/node-rdkafka`](https://github.com/terascope/node-rdkafka#why-does-this-fork-exists).
=> Add node@12 support

asset/asset.json, asset/package.json, asset/src/_kafka_clients/consumer-client.ts, asset/src/kafka_reader/fetcher.ts, package.json, packages/terafoundation_kafka_connector/package.json, yarn.lock
Update `node-rdkafka`/`librdafka` has increased the max wait time for the kafka fetcher. [`librdkafka@v1.0.0`](https://github.com/edenhill/librdkafka/releases/tag/v1.0.0) changed the default value for `enable.partition.eof` to `false`, while we ignore that particular error and would like it to be false, `node-rdkfakfa` has [logic](https://github.com/Blizzard/node-rdkafka/blob/d2fde4a3a905976b9333a1f6ce9e2780d78568e6/src/workers.cc#L523-L556) that is dependent on it for "consuming" batches.  I also removed setting the default consumer timeout because the consume timeout doesn't work as I would have that and setting that may extend the wait time as well.
This PR also the `librdkafka` version in `terafoundation_kafka_connector` to [`v1.2.2`](https://github.com/edenhill/librdkafka/releases/tag …
=> v2.4.2 - Fix wait issue

asset/asset.json, asset/package.json, asset/src/kafka_sender/interfaces.ts, asset/src/kafka_sender/processor.ts, asset/src/kafka_sender/schema.ts, package.json, test/kafka-sender-schema-spec.ts
The `kafka_sender` times increased when updating [librdkafka](https://github.com/edenhill/librdkafka/releases/tag/v1.0.0), the default value for `request.required.acks` was changed from `1` to `-1` (all) which could potentially be causing the performance issues.
This value is no configurable via `required_acks` on the `kafka_sender` operation config. The value is an integer, see the configuration description from librdkafka below.
```txt
This field indicates the number of acknowledgements the leader broker must receive from ISR brokers before responding to the request: 0=Broker does not send any response/ack to client, -1 or all=Broker will block until message is committed by all in sync replicas (ISRs). If there are less than min.insync.replicas (broker configuration) in the ISR set the …
```
=> v2.5.0 - set the default request.required.acks on the sender to 1

asset/asset.json, asset/package.json, asset/src/_kafka_clients/base-client.ts, asset/src/_kafka_clients/consumer-client.ts, asset/src/_kafka_clients/producer-client.ts, asset/src/kafka_dead_letter/api.ts, asset/src/kafka_reader/fetcher.ts, asset/src/kafka_sender/processor.ts, package.json, packages/terafoundation_kafka_connector/package.json, packages/terafoundation_kafka_connector/src/index.ts, packages/terafoundation_kafka_connector/src/interfaces.ts, test/helpers/kafka-admin.ts, test/helpers/kafka-data.ts, test/kafka-sender-spec.ts, test/kafka-slicer-spec.ts, yarn.lock
- Updates `terafoundation_kafka_connector` (0.5.3) to use official `node-rdkafka` npm package instead of our forked one.
- Fixes a `kafka_sender` issue that will  cause unnecessary flushing
- Updates a couple dev dependencies
=> v2.5.1 - Fix flush issue and use node-rdkafka official npm package

asset/asset.json, asset/package.json, asset/src/kafka_reader/index.ts, asset/src/kafka_sender/index.ts, asset/src/kafka_sender/interfaces.ts, asset/src/kafka_sender/processor.ts, asset/src/kafka_sender/schema.ts, asset/yarn.lock, package.json, packages/terafoundation_kafka_connector/package.json, test/kafka-fetcher-spec.ts, test/kafka-multisend-spec.ts, test/kafka-sender-spec.ts, yarn.lock
- adds support for a `connection_map` similar to how elasticsearch-assets bulk-sender works
- keys must be exact match to partition, this is to be used in combination with the new partition operations in standard assets
=> routing support in conjuction with routers from standard-assets

README.md, asset/asset.json, asset/package.json, asset/src/_kafka_clients/interfaces.ts, asset/src/_kafka_clients/producer-client.ts, asset/src/kafka_dead_letter/api.ts, asset/src/kafka_sender/processor.ts, package.json, test/helpers/config.ts, test/kafka-sender-spec.ts
refs #258 
Including `**` in the topic map will append the record's `standard:route` to the default topic and use that for the record's destination topic. If `standard:route` is not set, the default topic will be used for routing.
=> added ** routing for dynamic record topics

asset/asset.json, asset/package.json, docs/operations/kafka_sender.md, package.json
id_field explanation matches the kafka_sender_api docs, less technical and more purpose focused
=> kafka_sender docs clarification

asset/asset.json, asset/package.json, package.json, yarn.lock
This should fix the issue when using ```yarn setup``` so that it properly recompiles the build from scratch.
=> Add --force flag to setup command in package.json, update Jest, and bump asset version

asset/src/_kafka_clients/consumer-client.ts, yarn.lock
```
name            range     from        to       workspace                       url
❯◯ @types/convict  ^6.1.3    6.1.4    ❯  6.1.5    terafoundation_kafka_connector  https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/convict
◯ @types/jest     ^29.5.3   29.5.5   ❯  29.5.7   kafka-asset-bundle              https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/jest
◯ @types/node     ^18.14.2  18.14.2  ❯  18.18.7  kafka-asset-bundle              https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node
```
Node updated `timers.d.ts`, requiring a change to be made to `asset/src/_kafka_clients/consumer-client.ts`. The clearTimeout function now uses the timeout interface, not the timer interface.
=> Upgrade all outdated '@types' dependencies

packages/terafoundation_kafka_connector/test/kafka-connector-spec.ts, test/kafka_dead_letter/schema-spec.ts, test/kafka_reader/fetcher-spec.ts, test/kafka_reader/schema-spec.ts, test/kafka_sender/processor-spec.ts, yarn.lock
Update @types/jest from v29.5.6 to 29.5.7
Replace all instances of the deprecated `toThrowError()` function within tests with `toThrow()`.
=> Jest types bump and test fixes

package.json, yarn.lock
Update to latest ts-scripts. Add zookeeper to the stream test suite in package.json. This is necessary because the kafka docker image used in ts-scripts changed from `blacktop/kafka` to `confleunt/cp-kafka` and zookeeper is not built in to the kafka image anymore.
=> Add zookeeper and update ts-scripts version

asset/asset.json, asset/package.json, package.json, packages/terafoundation_kafka_connector/package.json, yarn.lock
Bump terafoundation_kafka_connector to 0.11.1 - node-rdkafa dependency was recently updated and we didn't bump then.
Bump kafka-asset to 3.5.2
Dependency updates:
```
Package        Current Wanted  Workspace                      Package Type    URL
@types/convict 6.1.5   6.1.6   terafoundation_kafka_connector devDependencies
@types/jest    29.5.7  29.5.8  kafka-asset-bundle             devDependencies
@types/node    18.18.7 18.18.9 kafka-asset-bundle             devDependencies
@types/uuid    9.0.6   9.0.7   kafka-asset-bundle             devDependencies
```
=> Update dependencies, bump terafoundation_kafka_connector and kafka-asset

.github/workflows/build-and-publish-asset.yml, .github/workflows/test-asset.yml, package.json, yarn.lock
- updated both `build-and-publish-asset.yaml` and `test-asset.yaml` to use a newer workflow that uses node `16.20.2` and `18.18.2` in CI.
- added `node-gyp@v9.4.1` as a dependency because node `18.18.2` no longer has it by default. Using `node-gyp` version `9.4.1` to support node 14. Any version above that will break node 14 compatibility.
=> update github workflows and add node-gyp

asset/package.json, package.json, packages/terafoundation_kafka_connector/package.json, yarn.lock
terafoundation-kafka-connector:
- dev-dependencies:
- @terascope/job-components from 0.64.0 to 0.65.0
kafka-assets:
- dependencies:
- @terascope/job-components from 0.64.0 to 0.65.0
kafka-asset-bundle:
- dev-dependencies:
- @terascope/job-components from 0.64.0 to 0.65.0 -@terascope/scripts from 0.62.0 to 0.63.0 -types:
- @types/jest from 29.5.10 to 29.5.11
- @types/node from 18.18.9 to 18.19.3
=> Dependency updates, 2023-12-11

asset/asset.json, asset/package.json, package.json
Bump to get package.json back in line with release versions.
=> bump: (patch) kafka-assets@3.5.5, kafka-asset-bundle@3.5.5

asset/asset.json, asset/package.json, asset/src/_kafka_clients/consumer-client.ts, asset/src/_kafka_clients/producer-client.ts, asset/src/kafka_reader/fetcher.ts, asset/src/kafka_sender_api/api.ts, asset/src/kafka_sender_api/sender.ts, package.json, yarn.lock
- add `_bytesConsumed`, `getBytesConsumed()` and `getPartitionCount()` to `asset/src/_kafka_clients/consumer-client.ts`
- add `bytes_consumed` and `partitions` promMetric to `kafkaFetcher`
- add `_bytesProduced` and `getBytesProduced()` to `asset/src/_kafka_clients/producer-client.ts`
- add `bytes_produced` promMetric to `kafkaSender`
=> Add prom metrics to kafka_fetcher and kafka_sender

asset/asset.json, asset/package.json, asset/src/kafka_reader/fetcher.ts, asset/src/kafka_sender_api/api.ts, asset/src/kafka_sender_api/sender.ts, package.json, packages/terafoundation_kafka_connector/package.json, yarn.lock
- Introduces backwards compatibility for teraslice versions before `v1.4.0`
- This fixes an issue where using a teraslice version older than version `v1.4.0` would throw `TypeError: this.promMetrics.addGauge is not a function`
- Bump **kafka-assets** to `v4.4.1`
- Updates the following dependencies:
- **@terascope/job-components** from `v0.74.2` to `v0.75.0`
ref: https://github.com/terascope/teraslice/issues/3625
=> Fix asset to work with Teraslice versions lower than v1.4.0

packages/terafoundation_kafka_connector/package.json, yarn.lock
Reverts terascope/kafka-assets#813
See issues:
https://github.com/Blizzard/node-rdkafka/issues/1087
https://github.com/confluentinc/librdkafka/issues/4793
=> Revert "Bump node-rdkafka from 3.0.1 to 3.1.0"

package.json, packages/terafoundation_kafka_connector/package.json, yarn.lock
- Update `ts-scripts` from 0.83.1 to 0.83.2
- Remove `KAFKA_VERSION=3.2` from all test scripts. This results in the kafka version being set to the default version in `ts-scripts`. The current version is 3.5.
=> Test on default kafka version from scripts.

asset/package.json, package.json, packages/terafoundation_kafka_connector/package.json, yarn.lock
- update @terascope/job-components from ^1.1.0 to ^1.2.0
- update @terascope/types from ^0.18.0 to ^1.0.0
- update @terascope/scripts from ^0.83.3 to ^1.0.0
- update teraslice-test-harness from ^1.1.0 to ^1.2.0
=> bundled updates

.github/workflows/build-and-publish-asset.yml, .github/workflows/daily-docker-cache.yml, .github/workflows/test-asset.yml, asset/asset.json, asset/package.json, package.json
This PR updates the github workflows hash to incorporate a fix for the upload-artifact@v4 action during build-and-publish-asset.yml workflow
Update kafka-assets from 5.0.0 to 5.0.1
=> Update GitHub workflow hash

package.json, packages/terafoundation_kafka_connector/package.json, yarn.lock
- remove --experimental-vm-modules flag from all ts-script test scripts
- Bump @terascope/scripts from 1.0.0 to 1.0.2
=> remove --experimental-vm-modules flag, update ts-scripts to 1.0.2

asset/asset.json, asset/package.json, asset/src/kafka_reader/slicer.ts, package.json
- Operation `kafka_reader` is now relocatable when running in `kubernetesV2` in teraslice
- This slicer is able to come back up in the event the pod is deleted in kubernetes. This includes use cases such as draining a node which would delete all resources from that node.
=> [Kafka-asset] Allow kafka to be relocatable

asset/asset.json, asset/package.json, package.json, packages/terafoundation_kafka_connector/package.json, yarn.lock
- terafoundation_kafka_connector: 
- bump node-rdkafka from 3.0.1 to 3.1.1
- This gets us past the issue with building node-rdkafa@3.1.0 on mac (#818)
- bump version from 1.0.1 to 1.1.0
- kafka-asset-bundle:
- bump @terascope/scripts from 1.4.2 to 1.5.0
- bump @types/node from 22.5.4 to 22.9.0
- bump uuid from 11.0.2 to 11.0.3
- bump version from 5.1.0 to 5.2.0
- kafka-assets:
- bump asset version from 5.1.0 to 5.2.0
=> Dependency updates 2024-11-12

asset/asset.json, asset/package.json, asset/src/_kafka_clients/interfaces.ts, asset/src/_kafka_clients/producer-client.ts, asset/src/kafka_dead_letter/api.ts, asset/src/kafka_dead_letter/interfaces.ts, asset/src/kafka_dead_letter/schema.ts, asset/src/kafka_sender_api/api.ts, asset/src/kafka_sender_api/schema.ts, asset/src/kafka_sender_api/sender.ts, docs/apis/kafka_sender_api.md, package.json, test/helpers/kafka-data.ts
- Adds new operations config to the `kafka_sender_api` called `max_buffer_kbytes_size` that allows the user to set the total message size sum in kilobytes allowed on the producer queue.
- Adds new logic to the kafka producer that will prevent an error in the case that the queue byte size is reached.
- Fixes false information in the `kafka_sender_api` to be correct
- Updates docs
- Adds logging to producer flush() actions 
- Bumps `kafka-assets` from `v5.1.0` to `v5.2.0`
Ref to issue  #755
=> Fix Kafka producer queue full bug

package.json, yarn.lock
Update ts-scripts from 1.5.0 to 1.5.1
- this fixes the bump script to use ~ instead of ^ when updating versions.
=> bump ts-scripts from 1.5.0 to 1.5.1

asset/package.json, package.json, packages/terafoundation_kafka_connector/package.json, yarn.lock
- bumps @terascope/eslint-config from 1.1.0 to 1.1.1
- bumps @terascope/job-components from 1.6.0 to 1.6.1
- bumps @terascope/scripts from 1.5.1 to 1.5.2
- bumps @terascope/types from 1.3.0 to 1.3.1
- bumps teraslice-test-harness from 1.2.0 to 1.2.1
- bumps @types/node from 22.9.0 to 22.9.3
=> bundled dependency updates

asset/asset.json, asset/package.json, package.json, packages/terafoundation_kafka_connector/package.json, yarn.lock
- Update node-rdkafka from 3.1.1 to 3.2.0
- this in turn updates `librdkafka` to version 2.6.0
- this allows for the use of cooperative rebalancing
- bump terafoundation_kafka_connector from 1.1. to 1.2.0
- bump kafka-asset from 5.2.0 to 5.3.0
ref: #869
=> Update node rdkafka to 3.2.0

asset/asset.json, asset/package.json, package.json, packages/terafoundation_kafka_connector/package.json, yarn.lock
- bump node-rdkafka from v3.2.0 to v3.2.1, which in turn bumps librdkafka from v2.6.0 to 2.6.1 
- bump terafoundation_kafka_connector from v1.2.0 to v1.2.1
- bump kafka-assets from v5.3.0 to v5.3.1
https://github.com/confluentinc/librdkafka/releases/tag/v2.6.1
=> update node-rdkafka from v3.2.0 to v3.2.1

asset/package.json, package.json, packages/terafoundation_kafka_connector/package.json, yarn.lock
This PR makes the following updates:
- kafka asset
- dependencies
- @terascope/job-components from 1.8.0 to 1.9.1
- @terascope/types from 1.3.1 to 1.4.1
- terafoundation_kafka_connector
- @terascope/job-components from 1.8.0 to 1.9.1
- workspace
- @terascope/eslint-config from 1.1.3 to 1.1.4
- @terascope/job-components from 1.8.0 to 1.9.1
- @terascope/scripts from 1.7.1 to 1.9.0
- @types/node from 22.10.2 to 22.10.5
- eslint from 9.17.0 to 9.18.0
- teraslice-test-harness from 1.2.1 to 1.3.1
- typescript from 5.2.2 to 5.7.3
- uuid from 11.0. to 11.0.5
=> bundled dependency update

README.md, asset/asset.json, asset/package.json, package.json, packages/terafoundation_kafka_connector/package.json, packages/terafoundation_kafka_connector/src/index.ts, packages/terafoundation_kafka_connector/src/interfaces.ts, packages/terafoundation_kafka_connector/src/schema.ts, yarn.lock
- Add `caCertificate` to the `kafkaConfig` options, allowing a CA cert string to be passed in through `terafoundation`
- NOTE: `node-rdkafka` will ignore `ssl_ca_location` if `caCertificate` is set
- bump terafoundation_kafka_connector from 1.2.1 to 1.3.0
- bump kafka-assets from 5.4.1 to 5.5.0
=> [terafoundation_kafka_connector] Add `caCertificate` option to provide rootCA to kafka config

asset/package.json, package.json, packages/terafoundation_kafka_connector/package.json, yarn.lock
- kafka-assets
- dependencies
- @terascope/job-components from 1.9.5 to 1.9.6
- kafka-asset-bundle
- @terascope/eslint-config from 1.1.6 to 1.1.7
- @terascope/job-components from 1.9.5 to 1.9.6
- @terascope/scripts from 1.10.3 to 1.10.4
- @types/node from 22.13.4 to 22.13.5
- eslint from 9.20.1 to 9.21.0
- ts-jest from 29.2.5 to 29.2.6
- uuid from 11.0.5 to 11.1.0
- terafoundation_kafka_connector
- @terascope/job-components from 1.9.5 to 1.9.6
- @terascope/scripts from 1.10.3 to 1.10.4
=> bundled dependency updates for 2-24-2025

asset/asset.json, asset/package.json, package.json, packages/terafoundation_kafka_connector/package.json, yarn.lock
- update `node-rdkafka` from 3.2.1 to 3.3.1
- bump `terafoundation_kafka_connector` from 1.3.0 to 1.4.0
- bump `kafka-asset` from 5.5.0 to 5.6.0
`node-rdkafka` now uses `librdkafka` 2.8.0
=> Update node rdkafka to 3.3.1

package.json, packages/terafoundation_kafka_connector/package.json, yarn.lock
- @terascope/scripts from 1.13.0 to 1.14.0
- @types/node from 22.13.13 to 22.13.14
- @types/semver from 7.5.8 to 7.7.0
- teraslice-test-harness from 1.3.3 to 1.3.4
- @terascope/scripts from 1.13.0 to 1.14.0
=> bundled dependency updates for 3-31-2025

package.json, packages/terafoundation_kafka_connector/package.json, yarn.lock
- @terascope/scripts from 1.15.1 to 1.15.2
- @types/node from 22.14.0 to 22.14.1
- ts-jest from 29.3.1 to 29.3.2
- typescript from 5.8.2 to 5.8.3
- @terascope/scripts from 1.15.1 to 1.15.2
=> bundled dependency updates for 4-14-2025

website/docusaurus.config.js
Algolia requires a certain format for its indices, so it needed to be updated in the docusaurus config.
=> [website] fix algolia doc index

asset/asset.json, asset/package.json, package.json, website/docusaurus.config.js
- set algolia `contextualSearch` to false on the docs website
- bump asset version from v5.6.1 to v5.6.2 to make a release that builds the docs
=> [website] turn off Algolia contextual search

asset/asset.json, asset/package.json, package.json, packages/terafoundation_kafka_connector/package.json, yarn.lock
- Update node-rdkafka from 3.3.1 to 3.4.0
- updates librdkafka from 2.8.0 to 2.10.0
- Update eslint from 9.25.1 to 9.26.0
- Bump terafoundation_kafka_connector from 1.4.0 to 1.5.0
- Bump kafka-asset from 5.6.2 to 5.7.0
=> Update node-rdkafka from 3.3.1 to 3.4.0

asset/package.json, package.json, packages/terafoundation_kafka_connector/package.json, yarn.lock
- dependencies
- @terascope/job-components from 1.10.0 to 1.10.1
- @terascope/eslint-config from 1.1.13 to 1.1.14
- @terascope/job-components from 1.10.0 to 1.10.1
- @terascope/scripts from 1.16.0 to 1.16.1
- @types/node from 22.15.3 to 22.15.17
- @terascope/job-components from 1.10.0 to 1.10.1
- @terascope/scripts from 1.16.0 to 1.16.1
=> bundled dependency updates for 5-12-2025

README.md, asset/asset.json, asset/package.json, docs/asset/apis/kafka_dead_letter.md, docs/asset/apis/kafka_reader_api.md, docs/asset/apis/kafka_sender_api.md, docs/packages/terafoundation_kafka_connector/overview.md, package.json
- fixes broken links in the docs
- bump: (patch) kafka-assets@5.8.1, kafka-asset-bundle@5.8.1 (this will create a release and build new docs)
=> Fix broken doc links

asset/asset.json, asset/package.json, package.json, packages/terafoundation_kafka_connector/package.json, yarn.lock
- update node rdkafka from v3.4.0 to v3.4.1
- this updates librdkafka from v2.10.0 to v2.10.1
- bump: (patch) terafoundation_kafka_connector@1.5.1
- bump: (patch) kafka-assets@5.8.2
- bump: (patch) kafka-asset-bundle@5.8.2
=> Update node rdkafka from v3.4.0 to v3.4.1

scripts/build-documentation.sh
This PR changes the `scripts/build-documentation.sh` script to force add `docs/packages/*/api` to the git staging area, then remove them after the docusaurus site builds. In some cases the website build will fail if the files do not have a git history.
=> [website, CI] temporarily add api docs to git staging area while building website

package.json, packages/terafoundation_kafka_connector/package.json, yarn.lock
- @terascope/eslint-config from 1.1.19 to 1.1.20
- @terascope/scripts from 1.20.1 to 1.20.2
- @types/node from 24.0.13 to 24.0.15
- @terascope/scripts from 1.20.1 to 1.20.2
=> bundled dependency updates for 7-21-2025

package.json, packages/terafoundation_kafka_connector/package.json, yarn.lock
This PR updates the following dependencies:
- @terascope/scripts: `v1.20.4`
- @types/node: `v24.2.0`
- ts-jest: `v29.4.1`
- typescript: `v5.9.2`
- @terascope/scripts: `v1.20.4`
=> bundled deps update 2025-08-04

asset/asset.json, asset/package.json, package.json, packages/terafoundation_kafka_connector/package.json, yarn.lock
- terafoundation_kafka_connector from 1.5.1 to 1.6.0
- dependencies
- node-rdkafka from 3.4.1 to 3.5.0
- this version bumps librdkafka from 2.10.1 to 2.11.0
=> Bump node-rdkafka to version 3.5.0

asset/asset.json, asset/package.json, asset/src/kafka_reader/fetcher.ts, asset/src/kafka_reader_api/api.ts, asset/src/kafka_reader_api/schema.ts, asset/src/kafka_sender/processor.ts, asset/src/kafka_sender_api/api.ts, asset/src/kafka_sender_api/schema.ts, docs/asset/apis/kafka_reader_api.md, docs/asset/apis/kafka_sender_api.md, package.json, test/kafka_reader_api/api-spec.ts, test/kafka_reader_api/schema-spec.ts, test/kafka_sender_api/api-spec.ts, test/kafka_sender_api/schema-spec.ts
- Adds new job option `rdkafka_options` to kafka reader and sender apis
- This allows for setting global kafka config properties through a job configuration
- https://github.com/confluentinc/librdkafka/blob/master/CONFIGURATION.md
- Adds testing for `rdkafka_options`
- Bumps Kafka-Asset from `v5.9.0` to `v5.10.0`
- Fixes logging within `kafka_sender` and `kafka_reader`
- Adds Kafka consumer and producer configuration debug logs
=> add rdkafka settings

asset/package.json, package.json, packages/terafoundation_kafka_connector/package.json, yarn.lock
- dependencies
- @terascope/job-components from 1.12.2 to 1.12.3
- @terascope/eslint-config from 1.1.24 to 1.1.25
- @terascope/job-components from 1.12.2 to 1.12.3
- @terascope/scripts from 1.21.5 to 1.21.6
- @types/node from 24.3.1 to 24.4.0
- teraslice-test-harness from 1.3.7 to 1.3.8
- uuid from 12.0.0 to 13.0.0
- @terascope/job-components from 1.12.2 to 1.12.3
- @terascope/scripts from 1.21.5 to 1.21.6
=> bundled dependency updates for 9-15-2025
